TileDB-Inc/TileDB-Spark

- installTileDBJava
- src/main/java/io/tiledb/spark/datasourcev2/DefaultSource.java
- src/main/java/io/tiledb/spark/datasourcev2/SubarrayBuilder.java
- src/main/java/io/tiledb/spark/datasourcev2/TileDBOptions.java
- src/main/java/io/tiledb/spark/datasourcev2/TileDBReaderFactory.java
- src/main/java/io/tiledb/spark/datasourcev2/TileDBSchemaConverter.java
- src/main/java/io/tiledb/spark/datasourcev2/TileDBWriterFactory.java
- src/test/scala/io/tiledb/spark/datasourcev2/PerformanceTest.scala
Add performance comparison test vs parquet
Add compression option. 
Fix minor bugs
> Add performance comparison test vs parquet

- README.md
Update build and spark shell instructions
> Update build and spark shell instructions

- README.md
- build.gradle
- src/main/java/io/tiledb/spark/TileDBDataReaderPartitionScan.java
- src/main/java/io/tiledb/spark/TileDBDataSourceOptions.java
- src/test/java/io/tiledb/spark/TileDBDataSourceReadTestBufferSizes.java
Improved incomplete query support and buffer reallocation
> Improved incomplete query support and buffer reallocation

- README.md
- build.gradle
- src/main/java/io/tiledb/spark/TileDBDataReaderPartitionScan.java
- src/main/java/io/tiledb/spark/TileDBDataSourceOptions.java
- src/main/java/io/tiledb/spark/TileDBDataSourceReader.java
- src/main/java/org/apache/spark/metrics/MetricsUpdate.java
- src/main/java/org/apache/spark/metrics/MetricsUpdater.java
- src/main/java/org/apache/spark/metrics/SimpleTimer.java
- src/main/java/org/apache/spark/metrics/TileDBMetricsSource.java
- src/main/java/org/apache/spark/metrics/TileDBMetricsTimer.java
- src/main/java/org/apache/spark/metrics/TileDBReadMetricsUpdater.java
- src/main/java/org/apache/spark/metrics/Timer.java
- src/test/java/io/tiledb/spark/TileDBDataSourceReadMetricsTest.java
- src/test/resources/log4j.properties
- src/test/resources/metrics.properties
This includes timers for most functions in the read path and the
partitioning.
> Add dropwizard metrics for spark metric collection

- src/main/java/io/tiledb/spark/Range.java
Convert the bucket to datatype of range for splits
> Convert the bucket to datatype of range for splits

- src/main/java/io/tiledb/spark/OptionDimPartition.java
remove stray println from OptionDimPartition
> remove stray println from OptionDimPartition

- src/main/java/io/tiledb/spark/TileDBDataReaderPartitionScan.java
Properly report input size of result buffers
> Properly report input size of result buffers

- scripts/emr-bootstrap/install-apache-arrow.sh
- scripts/emr-bootstrap/install-tiledb-spark.sh
> Add emr-bootstrap scripts

- .travis.yml
Upload compiled jar to github for releases
> Upload compiled jar to github for releases

- src/main/java/io/tiledb/spark/TileDBDataSourceWriter.java
> Fix offset filter for writes

- src/main/java/io/tiledb/spark/TileDBDataSourceWriter.java
> Fix append mode writes

- src/main/java/io/tiledb/spark/TileDBDataWriter.java
Close TileDB Resources on write commit
> Close TileDB Resources on write commit

- src/main/java/io/tiledb/spark/TileDBDataReaderPartitionScan.java
- src/main/java/io/tiledb/spark/TileDBDataWriter.java
- src/main/java/org/apache/spark/metrics/TileDBMetricsSource.java
- src/main/java/org/apache/spark/metrics/TileDBWriteMetricsUpdater.java
> Add write metrics

- src/main/java/io/tiledb/spark/TileDBDataSourceOptions.java
NOOP is used in other apis so let's support it here for consistency
> Add NOOP as alternative to NONE for filters

- src/main/java/io/tiledb/spark/TileDBDataSourceOptions.java
Add global order to layout options
> Add global order to layout options

- src/main/java/io/tiledb/spark/SubArrayRanges.java
- src/main/java/io/tiledb/spark/TileDBDataSourceReader.java
Fix computation of splits for a given bucket size
> Fix computation of splits for a given bucket size

- .travis.yml
- build.gradle
Upload metrics jar from Travis for Releases
> Upload metrics jar from Travis for Releases

- src/main/java/io/tiledb/spark/util.java
- src/test/java/io/tiledb/spark/SparkPartitioningTest.java
Resolves the following:
- https://app.clubhouse.io/tiledb-inc/story/1870/an-error-is-thrown-if-a-byte-dimension-is-set
- https://app.clubhouse.io/tiledb-inc/story/1869/an-error-is-thrown-if-a-short-dimension-is-set
> An error is thrown if a Byte dimension is [ch1870]

- build.gradle
- src/main/java/io/tiledb/spark/Range.java
- src/main/java/io/tiledb/spark/SubArrayRanges.java
- src/main/java/io/tiledb/spark/TileDBDataSourceOptions.java
- src/main/java/io/tiledb/spark/TileDBWriteSchema.java
- src/main/java/io/tiledb/spark/util.java
This PR contains the following:
1. Update to TileDB-Java 0.3.0
2. Improved documentation in order to remove warnings during compilation
3. Revised default domain bounds and tile extent
> Update to TileDB-Java 0.3.0

- azure-pipelines.yml
- build.gradle
- ci/tiledb-spark-linux.yml
Added the GitHub Release stage in Azure Pipelines for TileDB-Spark.
> Add GitHub Release Stage in Azure Pipelines

- src/test/java/io/tiledb/spark/SparkDatetypesTest.java
See added comments for more details.
> Fixed a bug in datetypes tests

- README.md
(cannot create 0.4.0 release from previous tag that GH has seen as a release)
> NFC commit to update the target tag

- .github/dependabot.yml
> adding dependabot for Spark and TileDB-Java dependencies

- README.md
Indicate project is in dormant state, and considered for archiving in near future.
> Indicate project is in dormant state, and considered for archiving in near future
